#!/usr/bin/env bash
# Transfers a file from Holberton's client to another.
# Check if the number of parameters is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables for better readability
path_2_file=$1
server_ip=$2
username=$3
ssh_key=$4

# Use scp to transfer the file to the user's home directory on the server
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_2_file" "$username"@"$server_ip":~/
