#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Holberton School" > /var/www/html/index.nginx-debian.html'
service nginx restart
